### ISSUE TITLE
Rename default branch to "main"

### ISSUE THREAD

**Issue by gadomski** [radiantearth/community-sprints#45]

**Comment by PowerChell** [comment]
FYI I am working on this but I don't have the permissions to edit the default branch. Trying to figure out who does!

**Comment by jedsundwall** [comment]
I *can* do this, but am unable to at the moment because there is another branch called `main`: https://github.com/radiantearth/community-sprints/tree/main

I'm too scared of Git to know what to do in this instance. How can we determine if we can delete the `main` branch? Once we do, I'll be able to rename master. @gadomski or @emmanuelmathot: please let me know if you have have any suggestions here.

**Comment by jedsundwall** [comment]
Never mind! We've sorted this out. The default branch is now called `main`.
